### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by nicoonoclaste** [rushmj/mpv-video-cutter#10]
Hi!

Your script is packaged in `nixpkgs`/NixOS, to make it convenient for our users, but currently they need to allow non-free software to use it (at least for that one package) as no license is specified for the script.

It would be super nice if you could specify (a free/open) one  :heart:

**Comment by rushmj** [comment]
ok,I have finished it.

**Comment by nicoonoclaste** [comment]
Thanks  <3
