### ISSUE TITLE
output directory say ~/Videos/mpv-cut?

### ISSUE THREAD

**Issue by fastrizwaan** [rushmj/mpv-video-cutter#5]
Hi, 

I want to add mpv-video-cutter to flatpak mpv; so, I want to have default output directory to ~/Videos/mpv-cut. How to do that?

Thanks a lot.

**Comment by rushmj** [comment]
find

>  `$output\`_cut_$file_name

 change it

**Comment by fastrizwaan** [comment]
Thanks I included mpv-video-cutter in mpv flatpak https://flathub.org/apps/details/io.mpv.Mpv
sources and modified lua scripts
https://github.com/flathub/io.mpv.Mpv
