### ISSUE TITLE
show time stamps when 'c' key is pressed 

### ISSUE THREAD

**Issue by fastrizwaan** [rushmj/mpv-video-cutter#6]
When we press 'c' key there is no prompt/info. whereas mpv_slicing shows Marked OSD

see
117 function toggle_mark()
https://github.com/Kagami/mpv_slicing/blob/master/slicing.lua

can mpv-video-cutter also show 'left' and 'right' trim timestamp on osd?

Thanks.

**Comment by rushmj** [comment]
I use lua's function 'print' to show  prompt in terminal,you can change this function to mp.osd_message()

**Comment by fastrizwaan** [comment]
thank you! works by replacing` print( `with `mp.osd_message(` in `cutter.lua` file
